cert:
  default_domain_name: "unixkoans.com"
  www_domain_name: "www.unixkoans.com"
  rss_domain_name: "planet.unixkoans.com"
  sync_domain_name: "sync.unixkoans.com"
  paste_domain_name: "paste.unixkoans.com"
  git_domain_name: "git.unixkoans.com"
  fonts_domain_name: "fonts.unixkoans.com"
