---
do:
  id: 39153100
  server_name: toyland
  ssh_key_name: toyland

droplet:
  size_id: 512mb
  region_id: sgp1
  image_id: debian-8-x64

linode:
  id: 2761863
  datacenter_id: 7
  plan_id: 1
  distro_id: 140
  server_name: toynode
