---
- name: Install postgresql
  apt:
    name: "{{ item }}"
    state: latest
    default_release: jessie-backports
  with_items:
  - postgresql
  - libpq-dev
  - python-psycopg2
  - postgresql-contrib

- name: Generate postgresql user password
  shell: openssl rand -base64 16 > {{ postgresql.password_file }}
  args:
    creates: "{{ postgresql.password_file }}"

- name: Get postgresql user password
  command: cat {{ postgresql.password_file }}
  register: postgresql_password
  changed_when: "postgresql_password.rc != 0"

- name: Create user
  postgresql_user:
    name: www-data
    password: "{{ postgresql_password }}"
  become: true
  become_user: postgres

- name: Create database
  postgresql_db:
    name: "{{ item }}"
    owner: www-data
  with_items:
  - ttrss
  - stikked
  become: true
  become_user: postgres

- name: Generate postgresql config
  template:
    src: postgresql.conf.j2
    dest: /etc/postgresql/9.6/main/postgresql.conf
    mode: 0644
  notify: Restart postgresql

- name: Add pg backup config
  template:
    src: pg_backup.conf.j2
    dest: /etc/postgresql/pg_backup.conf
    owner: postgres
    group: postgres

- name: Add pg backup script
  copy:
    src: pg_backup.sh
    dest: /usr/local/bin/pg_backup.sh
    mode: 0755

- name: Add cron
  cron:
    name: "backup postgresql"
    minute: "20"
    hour: "1"
    user: postgres
    job: "/usr/local/bin/pg_backup.sh -c /etc/postgresql/pg_backup.conf"
