---
- name: Install nginx
  apt:
    name: nginx-extras
    state: latest
    default_release: jessie-backports
    update_cache: yes

- name: Generate nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
  notify: Restart Nginx

- name: Add virtual host config
  template:
    src: "{{ item.src }}"
    dest: "/etc/nginx/sites-available/{{ item.dest }}"
    mode: 0644
  with_items:
  - { src: "planet.j2", dest: "planet" }
  - { src: "sync.j2", dest: "sync" }
  notify: Restart Nginx

- name: Enable virtual host
  file:
    src: "/etc/nginx/sites-available/{{ item.src }}"
    dest: "/etc/nginx/sites-enabled/{{ item.dest }}"
    state: link
  with_items:
  - { src: "planet", dest: "planet" }
  - { src: "sync", dest: "sync" }
