---
- hosts: local
  gather_facts: False
  become: True

  vars_prompt:
  - name: do_api_token_entry
    prompt: "Your DigitalOcean API access token"
    private: no

  roles:
  - droplet

- hosts: digital_ocean
  become: True

  vars_prompt:
  - name: tarsnap_password
    prompt: "Your Tarsnap account password"
    private: no

  roles:
  - common
  - unattendedupgrades
  - git-client
  - git-server
  - fail2ban
  - obnam
  - shadowsocks
  - role: certbot
    domains:
    - unixkoans.com
    - www.unixkoans.com
    - planet.unixkoans.com
    - sync.unixkoans.com
    - paste.unixkoans.com
    - git.unixkoans.com
    - fonts.unixkoans.com
  - role: nginx
    config:
      default: unixkoans.com
      planet: planet.unixkoans.com
      sync: sync.unixkoans.com
      paste: paste.unixkoans.com
      git: git.unixkoans.com
      ci: ci.unixkoans.com
      status: status.unixkoans.com
      dl: dl.unixkoans.com
      dashboard: dashboard.unixkoans.com
      shurl: shurl.unixkoans.com
  - postgresql
  - php
  - ttrss
  - syncthing
  - role: stikked
    paste_domain: paste.unixkoans.com
  - ansible
  - tarsnap
