---
- hosts: local
  gather_facts: False
  become: True

  vars_prompt:
  - name: linode_api_token_entry
    prompt: "Your Linode API access token"
    private: no

  roles:
  - linode

- hosts: linode
  become: True

  roles:
  - common
  - unattendedupgrades
  - fail2ban
  - git-client
  - shadowsocks
  - kcptun
  - php
  - role: certbot
    domains:
    - ci.unixkoans.com
    - status.unixkoans.com
    - dl.unixkoans.com
    - dashboard.unixkoans.com
    - shurl.unixkoans.com
  - nginx
  - jenkins
  - debian-packaging
  - pelican
  - role: lsyncd
    configs:
    - host: linuxtoy.org
      source: /var/lib/jenkins/workspace/pelican-linuxtoy/output
      target: /home/www/toy_source/output
    - host: unixkoans.com
      source: /var/www/html
      target: /var/www/html
  - mariadb
  - cachet
  - prometheus
  - grafana
  - yourls
