---
- hosts: local
  become: True

  vars_prompt:
  - name: do_api_token_entry
    prompt: "Your DigitalOcean API access token"
    private: no

  roles:
  - droplet

- hosts: digital_ocean
  become: True

  roles:
  - common
  - unattendedupgrades
  - git
  - fail2ban
  - obnam
  - shadowsocks
  - nginx
  - postgresql
  - php
  - ttrss
  - syncthing
  - stikked
  - certbot
