---
- hosts: local
  gather_facts: False
  become: True

  vars_prompt:
  - name: linode_api_token_entry
    prompt: "Your Linode API access token"
    private: no

  roles:
  - linode

- hosts: linode
  become: True

  roles:
  - common
  - unattendedupgrades
  - fail2ban
  - git-client
  - shadowsocks
  - kcptun
  - php
  - role: certbot
    domains:
    - ci.unixkoans.com
    - status.unixkoans.com
    - dl.unixkoans.com
    - dashboard.unixkoans.com
    - shurl.unixkoans.com
    - talk.linuxtoy.org
    - resume.linuxtoy.org
    - i.linuxtoy.org
  - role: nginx
    config:
      default: unixkoans.com
      planet: planet.unixkoans.com
      sync: sync.unixkoans.com
      paste: paste.unixkoans.com
      git: git.unixkoans.com
      ci: ci.unixkoans.com
      status: status.unixkoans.com
      dl: dl.unixkoans.com
      dashboard: dashboard.unixkoans.com
      shurl: shurl.unixkoans.com
      talk: talk.linuxtoy.org
      resume: resume.linuxtoy.org
      img: i.linuxtoy.org
  - jenkins
  - debian-packaging
  - pelican
  - role: lsyncd
    configs:
    - host: linuxtoy.org
      source: /var/lib/jenkins/workspace/pelican-linuxtoy/output
      target: /home/www/toy_source/output
    - host: unixkoans.com
      source: /var/www/html
      target: /var/www/html
  - mariadb
  - role: cachet
    status_domain: status.unixkoans.com
  - prometheus
  - role: grafana
    dashboard_domain: dashboard.unixkoans.com
  - role: yourls
    shurl_domain: shurl.unixkoans.com
