---
- hosts: local
  gather_facts: False
  become: True

  vars_prompt:
  - name: vultr_api_token_entry
    prompt: "Your Vultr API access token"
    private: no

  roles:
  - vultr

- hosts: vultr
  become: True

  roles:
  - common
  - unattendedupgrades
  - fail2ban
  - git-client
  - shadowsocks
  - kcptun
  - ansible
  - openjdk
  - role: user
    user_metadata:
    - user_name: jenkins
      group_name: jenkins
      user_home: /var/lib
      github_user: xuxiaodong
    - user_name: toyland
      group_name: wheel
      user_home: /home
      github_user: xuxiaodong
  - debian-packaging
  - pelican
  - docker
