---
- hosts: local
  gather_facts: False
  become: True

  vars_prompt:
  - name: vultr_api_token_entry
    prompt: "Your Vultr API access token"
    private: no

  roles:
  - vultr

- hosts: vultr
  become: True

  roles:
  - common
  - unattendedupgrades
  - fail2ban
  - git-client
  - git-server
  - shadowsocks
  - kcptun
  - ansible
  - openjdk
  - role: user
    user_metadata:
    - user_name: jenkins
      group_name: jenkins
      user_home: /var/lib
      github_user: xuxiaodong
    - user_name: toyland
      group_name: wheel
      user_home: /home
      github_user: xuxiaodong
  - debian-packaging
  - pelican
  - docker
  - obnam
  - role: certbot
    domains:
    - unixkoans.com
    - www.unixkoans.com
    - planet.unixkoans.com
    - sync.unixkoans.com
    - paste.unixkoans.com
    - git.unixkoans.com
    - fonts.unixkoans.com
  - role: nginx
    config:
      default: unixkoans.com
      planet: planet.unixkoans.com
      sync: sync.unixkoans.com
      paste: paste.unixkoans.com
      git: git.unixkoans.com
  - postgresql
  - php
  - ttrss
  - role: stikked
    paste_domain: paste.unixkoans.com
  - syncthing
