---
- name: Create group
  group:
    name: "{{ item.group_name }}"
    state: present
  with_items: "{{ user_metadata }}"

- name: Create user
  user:
    name: "{{ item.user_name }}"
    state: present
    group: "{{ item.group_name }}"
    home: "{{ item.user_home }}/{{ item.user_name }}"
  with_items: "{{ user_metadata }}"

- name: Add sudo
  lineinfile:
    name: /etc/sudoers
    state: present
    regexp: "^%{{ item.group_name }} "
    line: "%{{ item.group_name }} ALL=(ALL) NOPASSWD: ALL"
  with_items: "{{ user_metadata }}"
