---
- name: Install requirements
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - build-essential
  - fakeroot
  - devscripts
  - debhelper
  - lintian
  - debootstrap
  - pbuilder

- name: Generate config
  template:
    src: pbuilderrc.j2
    dest: /var/lib/jenkins/.pbuilderrc

- name: Create base tarball
  command: pbuilder create
  args:
    creates: /var/cache/pbuilder/base.tgz

- name: Add cron
  cron:
    name: "Update pbuilder"
    minute: "30"
    hour: "1"
    user: root
    job: "pbuilder update"
