---
- name: Install certbot
  apt:
    name: "{{ item }}"
    state: latest
    default_release: jessie-backports
    update_cache: yes
  with_items:
  - certbot
  - python-certbot-nginx

- name: Generate config
  template:
    src: cli.ini.j2
    dest: /etc/letsencrypt/cli.ini
    mode: 0644

- name: Get cert
  shell: certbot certonly -c /etc/letsencrypt/cli.ini

- name: Add cron
  cron:
    name: "renew cert"
    minute: "52"
    hour: "0,12"
    user: root
    job: "certbot renew -q --pre-hook \"systemctl stop nginx\" --post-hook \"systemctl start nginx\""
