---
- name: Install certbot
  apt:
    name: "{{ item }}"
    state: present
    default_release: jessie-backports
  with_items:
  - certbot

- name: Generate config
  template:
    src: cli.ini.j2
    dest: /etc/letsencrypt/cli.ini
    mode: 0644

- name: Get cert
  command: certbot certonly -c /etc/letsencrypt/cli.ini
  register: run_certbot
  changed_when: "run_certbot.rc != 0"

# See also: https://github.com/certbot/certbot/issues/4096
- name: Add cron
  cron:
    name: "renew cert"
    minute: "52"
    hour: "0,12"
    user: root
    job: "certbot certonly -q -c /etc/letsencrypt/cli.ini"
