---
- name: Add apt key
  apt_key:
    url: "https://pkg.jenkins.io/debian/jenkins.io.key"
    state: present

- name: Add apt repo
  apt_repository:
    repo: deb http://pkg.jenkins.io/debian-stable binary/
    state: present

- name: Install package
  apt:
    name: jenkins
    state: present

- name: Add sudoer
  lineinfile:
    dest: /etc/sudoers
    regexp: '^jenkins'
    line: 'jenkins ALL=(ALL) NOPASSWD: ALL'

- name: Git config
  git_config:
    name: "user.{{ item.key }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
  - { key: "name", value: "{{ user.full_name }}" }
  - { key: "email", value: "{{ user.email }}" }
  become: True
  become_method: su
  become_user: jenkins
