---
- name: Install package
  apt:
    name: fail2ban
    state: latest
    default_release: jessie-backports

- name: Enable service
  systemd:
    name: fail2ban
    state: started
    enabled: yes
