---
- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    default_release: jessie-backports
  with_items:
  - prometheus
  - prometheus-alertmanager
  - prometheus-node-exporter
  - prometheus-pushgateway

- name: Generate config
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    mode: 0644
  notify: Restart prometheus
