---
- name: Install shadowsocks-libev
  apt:
    name: shadowsocks-libev
    state: present
    default_release: jessie-backports

- name: Generate Shadowsocks password
  shell: openssl rand -base64 48 > {{ shadowsocks.password_file }}
  args:
    creates: "{{ shadowsocks.password_file }}"

- name: Get Shadowsocks password
  command: cat {{ shadowsocks.password_file }}
  register: shadowsocks_password
  changed_when: "shadowsocks_password.rc != 0"

- name: Generate Shadowsocks config
  template:
    src: config.json.j2
    dest: "{{ shadowsocks.location }}/config.json"
    mode: 0640
    owner: nobody
    group: nogroup
  notify: Restart shadowsocks-libev
