---
- name: Add backports repository
  apt_repository:
    repo: "deb http://ftp.debian.org/debian jessie-backports main"
    state: present

- name: Install common packages
  apt:
    name: "{{ item }}"
    state: present
    default_release: jessie-backports
    update_cache: yes
  with_items:
  - apt-transport-https
  - htop
  - iotop
  - rsync
  - python-pip
  - virtualenv

- name: Add personal repository
  apt_repository:
    repo: "deb https://dl.unixkoans.com/ unstable/"
    state: present

- name: Disable service
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  ignore_errors: yes
  with_items:
  - atd
  - nfs-common
  - rpcbind

- name: Sysctl config
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    ignoreerrors: yes
  with_items:
  - name: net.ipv4.tcp_fastopen
    value: 3
  - name: net.ipv4.tcp_slow_start_after_idle
    value: 0
  - name: net.core.busy_read
    value: 50
  - name: net.core.busy_poll
    value: 50
  - name: kernel.sched_min_granularity_ns
    value: 10000000
  - name: kernel.sched_wakeup_granularity_ns
    value: 15000000
  - name: vm.dirty_ratio
    value: 30
  - name: vm.dirty_background_ratio
    value: 10
  - name: vm.swappiness
    value: 30

- name: Check ssh key exist
  command: test -e /root/.ssh/id_rsa.pub
  register: ssh_key
  ignore_errors: yes
  changed_when: "ssh_key.rc != 0"

- name: Get ssh key
  get_url:
    url: "https://github.com/{{ user.name }}.keys"
    dest: /root/.ssh/id_rsa.pub
    mode: 0600
  ignore_errors: yes
  when: "ssh_key.rc != 0"
