---
- name: Add backports repository
  apt_repository:
    repo: "deb http://ftp.sg.debian.org/debian jessie-backports main"
    state: present

- name: Install common packages
  apt:
    name: "{{ item }}"
    state: latest
    default_release: jessie-backports
    update_cache: yes
  with_items:
  - apt-transport-https
  - htop
  - iotop

- name: Disable service
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
  - atd
  - nfs-common
  - rpcbind

- name: Enable TCP fast open
  sysctl:
    name: net.ipv4.tcp_fastopen
    value: 3
    state: present

- name: Disable slow start after idle
  sysctl:
    name: net.ipv4.tcp_slow_start_after_idle
    value: 0
    state: present

- name: Set sched min granularity
  sysctl:
    name: kernel.sched_min_granularity_ns
    value: 10000000
    state: present
    ignoreerrors: yes

- name: Set sched wakeup granularity
  sysctl:
    name: kernel.sched_wakeup_granularity_ns
    value: 15000000
    state: present
    ignoreerrors: yes

- name: Set dirty ratio
  sysctl:
    name: vm.dirty_ratio
    value: 30
    state: present
    ignoreerrors: yes

- name: Set dirty background ratio
  sysctl:
    name: vm.dirty_background_ratio
    value: 10
    state: present
    ignoreerrors: yes

- name: Set swappiness
  sysctl:
    name: vm.swappiness
    value: 30
    state: present
    ignoreerrors: yes
