---
- name: Install php
  apt:
    name: "{{ item }}"
    state: present
    default_release: jessie-backports
  with_items:
  - php5-fpm
  - php5-json
  - php5-curl
  - php5-gd
  - php5-pgsql
  - php5-mysql
  - php5-mcrypt
  - php5-apcu
  - php5-readline

- name: Generate php fpm config
  template:
    src: www.conf.j2
    dest: /etc/php5/fpm/pool.d/www.conf
    mode: 0644
  notify: Restart fpm
